### ISSUE TITLE
Get a girlfriend 👩🏼

### ISSUE THREAD

**Issue by enjikaka** [enjikaka/jeremyjs#1]

**Comment by n1kolayb** [comment]
Was trying to find a solution in stackoverflow, but nothing so far. Looks like you gotta do it yourself =)

**Comment by n1kolayb** [comment]
Seems like you might have a COMMITment issue! =)

**Comment by enjikaka** [comment]
Thanks for the input! I rather think I commit too fast. Don't even have time to reflect on the commit message... I'll add the bug flag too then!

**Comment by mekwall** [comment]
Isn't this out of scope, at least for 1.0? Wouldn't it be better to start off with a girlfriend for 1.0?

**Comment by enjikaka** [comment]
Can't argue with that @mekwall. Will update title accordingly.

**Comment by mekwall** [comment]
You should add this to milestone 1.0 and #5 to 2.0.

**Comment by enjikaka** [comment]
I have a Tinder date this weekend :D

**Comment by enjikaka** [comment]
Me and a girl in Skåne now have a [💛](https://emojipedia.org/snapchat/) on Snapchat. 

![](http://memecrunch.com/meme/12AAT/so-i-guess-you-can-say-things-are-getting-pretty-serious/image.png?w=500&c=1)

**Comment by enjikaka** [comment]
Also, that is not the Tinder date. 🙈

**Comment by enjikaka** [comment]
The Tinder date went so good!!

**Comment by enjikaka** [comment]
The previously mentioned date (banana girl) went south. I am now processing other candidates.

**Comment by enjikaka** [comment]
Score!
