### ISSUE TITLE
Get a car 🚙

### ISSUE THREAD

**Issue by enjikaka** [enjikaka/jeremyjs#2]
Tesla Model 3 reservation was made 2017-08-04. Estimated delivery early 2019.

**Comment by enjikaka** [comment]
Order made 2018-12-07. Estimated delivery February/March 2019.
Went with Deep Blue Metallic, long range and all wheel drive. 💸

**Comment by enjikaka** [comment]
I got my Tesla Model 3 in March this year. Closing! 💃

**Comment by chill5018** [comment]
Not marked as done in the project @enjikaka

**Comment by enjikaka** [comment]
@chill5018 Oh. I'll fix that. Thanks for the heads up!
