### ISSUE TITLE
Get a house 🏡

### ISSUE THREAD

**Issue by enjikaka** [enjikaka/jeremyjs#3]
Already have an apartment, but I really want a house with a garden. 😍

**Comment by stonetwig** [comment]
Blocked because of the work that is being done on #2, this should be higher priority

**Comment by enjikaka** [comment]
Have two years of BSU savings now. Issue #2 blocks further savings for a while but I'll do my best to save up as much as I can so I can get a house in the countryside asap. 🏡

**Comment by enjikaka** [comment]
I signed contract for a house back in February. Moving in this summer.

Here's the prospect! https://drive.google.com/open?id=1G_apLUkrl1Bi64i4GikIbWjaIWpBAL4s
