### ISSUE TITLE
The bathroom light is broken 🕯🚻

### ISSUE THREAD

**Issue by enjikaka** [enjikaka/jeremyjs#4]
When I flip the switch in my bathroom it does not turn on.

**Comment by enjikaka** [comment]
Tried changing the light bulbs (G4). But it didn't work after that either. They are spotlights built into the bathroom mirror.... They both stopped working at the same time so maybe there is another problem... 🤔

**Comment by enjikaka** [comment]
My father came for visit. We dismounted the mirror and investigated. The 240 V to 12 V transformator is dead. Need to buy a new one.

**Comment by enjikaka** [comment]
Ok, so I found this: 

https://www.kjell.com/no/produkter/elektro-og-verktoy/stromforsyning/transformatorer/led-transformatorer/led-transformator-lavprofil-6-w-p44147?gclid=EAIaIQobChMIz5rW1Lb42QIVlJAYCh2kFALeEAQYBCABEgKrdPD_BwE

The headroom is quite small behind the mirror where the transformator is to be placed, so this 11 mm high one should do the trick! It will have some space for cooling off. ⛄️

**Comment by mekwall** [comment]
How is this a bug when #3 hasn't been closed yet?

**Comment by enjikaka** [comment]
It's in my apartment. Added more information to #3.

**Comment by enjikaka** [comment]
![](https://i.imgur.com/IT9qgaz.jpg)

The transformator is now installed and working!

**Comment by josven** [comment]
This is clearly a hardware problem.
